-- Workflow Automations Phase 1 (config/domain foundation only). Adds the
-- one new WorkflowAutomation table, plus one additive enum value
-- (ActivityEntityType.WORKFLOW_AUTOMATION, for this phase's own domain
-- layer to record config create/update/enable/disable/archive events --
-- see WorkflowAutomation's own schema doc comment) -- no other schema
-- change. Purely additive: no existing table/column is altered or
-- dropped, and no backfill is required (there is no pre-existing data for
-- this brand-new table, and an added enum value needs none).
--
-- One pair of statements generated by the raw `prisma migrate diff` used
-- to produce this file was deliberately removed before it was ever
-- applied anywhere: a spurious DROP CONSTRAINT/ADD CONSTRAINT pair each
-- for Client.statusDefinitionId, Lead.statusDefinitionId, and
-- Project.statusDefinitionId. This is the same pre-existing, unrelated
-- schema drift documented and stripped identically in every migration
-- since 20260927090000_add_lead_capture_forms_foundation (drift between
-- migration 20260926090000_add_custom_statuses_foundation, which created
-- those three FKs as `NO ACTION ... DEFERRABLE INITIALLY DEFERRED`, and
-- the current schema.prisma's plain `onDelete: Restrict`). Not fixed
-- here, per the same established, repeated instruction.

-- AlterEnum
ALTER TYPE "ActivityEntityType" ADD VALUE 'WORKFLOW_AUTOMATION';

-- CreateTable
CREATE TABLE "WorkflowAutomation" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "isEnabled" BOOLEAN NOT NULL DEFAULT true,
    "triggerEntityType" "ActivityEntityType" NOT NULL,
    "triggerAction" "ActivityAction" NOT NULL,
    "conditions" JSONB NOT NULL DEFAULT '[]',
    "actions" JSONB NOT NULL DEFAULT '[]',
    "createdByUserId" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "archivedAt" TIMESTAMP(3),

    CONSTRAINT "WorkflowAutomation_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "WorkflowAutomation_organizationId_archivedAt_idx" ON "WorkflowAutomation"("organizationId", "archivedAt");

-- CreateIndex
CREATE INDEX "WorkflowAutomation_organizationId_triggerEntityType_trigger_idx" ON "WorkflowAutomation"("organizationId", "triggerEntityType", "triggerAction", "archivedAt", "isEnabled");

-- AddForeignKey
ALTER TABLE "WorkflowAutomation" ADD CONSTRAINT "WorkflowAutomation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkflowAutomation" ADD CONSTRAINT "WorkflowAutomation_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
