-- Recurring Invoices Phase 1 (domain foundation only). Adds the recurring-
-- invoice schedule/template/occurrence-ledger schema plus Invoice's own
-- nullable origin pointer. No cron route, no Staff UI, no Portal change —
-- this migration is schema-only.
--
-- Three statements generated by the raw `prisma migrate dev --create-only`
-- diff were deliberately removed from this file before it was ever
-- applied anywhere: a spurious DROP CONSTRAINT/ADD CONSTRAINT pair each
-- for Client.statusDefinitionId, Lead.statusDefinitionId, and
-- Project.statusDefinitionId. This is the same pre-existing, unrelated
-- schema drift documented and stripped identically in every migration
-- since 20260927090000_add_lead_capture_forms_foundation (drift between
-- migration 20260926090000_add_custom_statuses_foundation, which created
-- those three FKs as `NO ACTION ... DEFERRABLE INITIALLY DEFERRED`, and
-- the current schema.prisma's plain `onDelete: Restrict`). Not fixed
-- here, per the same established, repeated instruction.

-- CreateEnum
CREATE TYPE "RecurrenceFrequency" AS ENUM ('WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY');

-- CreateEnum
CREATE TYPE "RecurringInvoiceStatus" AS ENUM ('ACTIVE', 'PAUSED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "RecurringInvoiceOccurrenceStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED');

-- AlterEnum
ALTER TYPE "ActivityEntityType" ADD VALUE 'RECURRING_INVOICE';

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "recurringInvoiceId" UUID;

-- CreateTable
CREATE TABLE "RecurringInvoice" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "clientId" UUID NOT NULL,
    "projectId" UUID,
    "name" TEXT,
    "status" "RecurringInvoiceStatus" NOT NULL DEFAULT 'ACTIVE',
    "frequency" "RecurrenceFrequency" NOT NULL,
    "anchorDay" INTEGER NOT NULL,
    "nextIssueDate" TIMESTAMP(3) NOT NULL,
    "invoiceNumberPrefix" TEXT NOT NULL,
    "nextSequence" INTEGER NOT NULL DEFAULT 1,
    "dueDateOffsetDays" INTEGER,
    "currency" TEXT NOT NULL,
    "discountType" "InvoiceDiscountType" NOT NULL DEFAULT 'NONE',
    "discountValue" DECIMAL(10,2),
    "taxRatePercent" DECIMAL(5,2),
    "taxLabel" "InvoiceTaxLabel" NOT NULL DEFAULT 'TAX',
    "notes" TEXT,
    "internalNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecurringInvoice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecurringInvoiceLineItem" (
    "id" UUID NOT NULL,
    "recurringInvoiceId" UUID NOT NULL,
    "description" TEXT NOT NULL,
    "quantity" DECIMAL(10,3) NOT NULL,
    "unitPrice" DECIMAL(10,2) NOT NULL,
    "position" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecurringInvoiceLineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecurringInvoiceOccurrence" (
    "id" UUID NOT NULL,
    "recurringInvoiceId" UUID NOT NULL,
    "occurrenceDate" TIMESTAMP(3) NOT NULL,
    "status" "RecurringInvoiceOccurrenceStatus" NOT NULL DEFAULT 'PENDING',
    "claimedAt" TIMESTAMP(3),
    "claimToken" TEXT,
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "invoiceId" UUID,
    "failureReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecurringInvoiceOccurrence_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "RecurringInvoice_organizationId_idx" ON "RecurringInvoice"("organizationId");

-- CreateIndex
CREATE INDEX "RecurringInvoice_organizationId_status_idx" ON "RecurringInvoice"("organizationId", "status");

-- CreateIndex
CREATE INDEX "RecurringInvoice_organizationId_clientId_idx" ON "RecurringInvoice"("organizationId", "clientId");

-- CreateIndex
CREATE UNIQUE INDEX "RecurringInvoiceLineItem_recurringInvoiceId_position_key" ON "RecurringInvoiceLineItem"("recurringInvoiceId", "position");

-- CreateIndex
CREATE UNIQUE INDEX "RecurringInvoiceOccurrence_invoiceId_key" ON "RecurringInvoiceOccurrence"("invoiceId");

-- CreateIndex
CREATE UNIQUE INDEX "RecurringInvoiceOccurrence_recurringInvoiceId_occurrenceDat_key" ON "RecurringInvoiceOccurrence"("recurringInvoiceId", "occurrenceDate");

-- CreateIndex
CREATE INDEX "Invoice_recurringInvoiceId_idx" ON "Invoice"("recurringInvoiceId");

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_recurringInvoiceId_fkey" FOREIGN KEY ("recurringInvoiceId") REFERENCES "RecurringInvoice"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecurringInvoice" ADD CONSTRAINT "RecurringInvoice_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecurringInvoice" ADD CONSTRAINT "RecurringInvoice_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecurringInvoice" ADD CONSTRAINT "RecurringInvoice_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecurringInvoiceLineItem" ADD CONSTRAINT "RecurringInvoiceLineItem_recurringInvoiceId_fkey" FOREIGN KEY ("recurringInvoiceId") REFERENCES "RecurringInvoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecurringInvoiceOccurrence" ADD CONSTRAINT "RecurringInvoiceOccurrence_recurringInvoiceId_fkey" FOREIGN KEY ("recurringInvoiceId") REFERENCES "RecurringInvoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecurringInvoiceOccurrence" ADD CONSTRAINT "RecurringInvoiceOccurrence_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE SET NULL ON UPDATE CASCADE;
