-- Communication Timeline Phase 1 (schema/domain foundation only). Adds
-- one new table (TimelineNote) plus one new enum (TimelineNoteEntityType)
-- -- no other schema change. Purely additive: no existing table/column is
-- touched, no backfill is required (there is no pre-existing data for
-- this brand-new table).
--
-- One set of statements generated by the raw `prisma migrate diff` used
-- to produce this file was deliberately removed before it was ever
-- applied anywhere: a spurious DROP CONSTRAINT/ADD CONSTRAINT pair each
-- for Client.statusDefinitionId, Lead.statusDefinitionId, and
-- Project.statusDefinitionId. This is the same pre-existing, unrelated
-- schema drift documented and stripped identically in every migration
-- since 20260927090000_add_lead_capture_forms_foundation (drift between
-- migration 20260926090000_add_custom_statuses_foundation, which created
-- those three FKs as `NO ACTION ... DEFERRABLE INITIALLY DEFERRED`, and
-- the current schema.prisma's plain `onDelete: Restrict`). Not fixed
-- here, per the same established, repeated instruction.

-- CreateEnum
CREATE TYPE "TimelineNoteEntityType" AS ENUM ('CLIENT', 'LEAD');

-- CreateTable
CREATE TABLE "TimelineNote" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "authorId" UUID,
    "entityType" "TimelineNoteEntityType" NOT NULL,
    "entityId" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "editedAt" TIMESTAMP(3),
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TimelineNote_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TimelineNote_organizationId_entityType_entityId_createdAt_i_idx" ON "TimelineNote"("organizationId", "entityType", "entityId", "createdAt", "id");

-- AddForeignKey
ALTER TABLE "TimelineNote" ADD CONSTRAINT "TimelineNote_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TimelineNote" ADD CONSTRAINT "TimelineNote_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
