-- Recurring Invoices Phase 2B-1 (due batch job + cron route foundation).
-- Adds the one composite index the new due-batch query actually reads
-- (status = 'ACTIVE' AND nextIssueDate <= today) — no other schema change.
--
-- One statement generated by the raw `prisma migrate dev --create-only`
-- diff was deliberately removed from this file before it was ever applied
-- anywhere: a spurious DROP CONSTRAINT/ADD CONSTRAINT pair each for
-- Client.statusDefinitionId, Lead.statusDefinitionId, and
-- Project.statusDefinitionId. This is the same pre-existing, unrelated
-- schema drift documented and stripped identically in every migration
-- since 20260927090000_add_lead_capture_forms_foundation (drift between
-- migration 20260926090000_add_custom_statuses_foundation, which created
-- those three FKs as `NO ACTION ... DEFERRABLE INITIALLY DEFERRED`, and
-- the current schema.prisma's plain `onDelete: Restrict`). Not fixed
-- here, per the same established, repeated instruction.

-- CreateIndex
CREATE INDEX "RecurringInvoice_status_nextIssueDate_idx" ON "RecurringInvoice"("status", "nextIssueDate");
