-- Tags V1 Phase 1 (schema/domain foundation only). Adds the two new
-- Tag/TagAssignment tables plus one new enum (TagEntityType) -- no other
-- schema change. Purely additive: no existing table/column is touched,
-- no backfill is required (there is no pre-existing data for either
-- brand-new table).
--
-- One pair of statements generated by the raw `prisma migrate diff` used
-- to produce this file was deliberately removed before it was ever
-- applied anywhere: a spurious DROP CONSTRAINT/ADD CONSTRAINT pair each
-- for Client.statusDefinitionId, Lead.statusDefinitionId, and
-- Project.statusDefinitionId. This is the same pre-existing, unrelated
-- schema drift documented and stripped identically in every migration
-- since 20260927090000_add_lead_capture_forms_foundation (drift between
-- migration 20260926090000_add_custom_statuses_foundation, which created
-- those three FKs as `NO ACTION ... DEFERRABLE INITIALLY DEFERRED`, and
-- the current schema.prisma's plain `onDelete: Restrict`). Not fixed
-- here, per the same established, repeated instruction.

-- CreateEnum
CREATE TYPE "TagEntityType" AS ENUM ('CLIENT', 'LEAD');

-- CreateTable
CREATE TABLE "Tag" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "normalizedName" TEXT NOT NULL,
    "color" "CustomStatusColor",
    "archivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Tag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TagAssignment" (
    "id" UUID NOT NULL,
    "organizationId" UUID NOT NULL,
    "tagId" UUID NOT NULL,
    "entityType" "TagEntityType" NOT NULL,
    "entityId" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TagAssignment_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Tag_organizationId_archivedAt_idx" ON "Tag"("organizationId", "archivedAt");

-- CreateIndex
CREATE UNIQUE INDEX "Tag_organizationId_normalizedName_key" ON "Tag"("organizationId", "normalizedName");

-- CreateIndex
CREATE INDEX "TagAssignment_organizationId_entityType_entityId_idx" ON "TagAssignment"("organizationId", "entityType", "entityId");

-- CreateIndex
CREATE UNIQUE INDEX "TagAssignment_tagId_entityType_entityId_key" ON "TagAssignment"("tagId", "entityType", "entityId");

-- AddForeignKey
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagAssignment" ADD CONSTRAINT "TagAssignment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagAssignment" ADD CONSTRAINT "TagAssignment_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;
