-- Workflow Automations Phase 2 (execution ledger). Adds the one new
-- WorkflowAutomationRun table plus its status enum -- no other schema
-- change. Purely additive: no existing table/column is touched, no
-- backfill is required (there is no pre-existing data for this
-- brand-new table).
--
-- One pair of statements generated by the raw `prisma migrate diff` used
-- to produce this file was deliberately removed before it was ever
-- applied anywhere: a spurious DROP CONSTRAINT/ADD CONSTRAINT pair each
-- for Client.statusDefinitionId, Lead.statusDefinitionId, and
-- Project.statusDefinitionId. This is the same pre-existing, unrelated
-- schema drift documented and stripped identically in every migration
-- since 20260927090000_add_lead_capture_forms_foundation (drift between
-- migration 20260926090000_add_custom_statuses_foundation, which created
-- those three FKs as `NO ACTION ... DEFERRABLE INITIALLY DEFERRED`, and
-- the current schema.prisma's plain `onDelete: Restrict`). Not fixed
-- here, per the same established, repeated instruction.

-- CreateEnum
CREATE TYPE "WorkflowAutomationRunStatus" AS ENUM ('SUCCEEDED', 'FAILED');

-- CreateTable
CREATE TABLE "WorkflowAutomationRun" (
    "id" UUID NOT NULL,
    "workflowAutomationId" UUID NOT NULL,
    "activityId" UUID NOT NULL,
    "status" "WorkflowAutomationRunStatus" NOT NULL,
    "failureReason" TEXT,
    "failedActionIndex" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WorkflowAutomationRun_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "WorkflowAutomationRun_workflowAutomationId_createdAt_idx" ON "WorkflowAutomationRun"("workflowAutomationId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "WorkflowAutomationRun_workflowAutomationId_activityId_key" ON "WorkflowAutomationRun"("workflowAutomationId", "activityId");

-- AddForeignKey
ALTER TABLE "WorkflowAutomationRun" ADD CONSTRAINT "WorkflowAutomationRun_workflowAutomationId_fkey" FOREIGN KEY ("workflowAutomationId") REFERENCES "WorkflowAutomation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkflowAutomationRun" ADD CONSTRAINT "WorkflowAutomationRun_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
